name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        pip install pytest-golden
        pip install coverage
        pip install pep8
        pip install mypy
    - name: Code check
      run: |
        find . -type f -name "*.py" | xargs -t python3-coverage report
        find . -type f -name "*.py" | xargs -t pep8 --ignore=E501
        find . -type f -name "*.py" | xargs -t mypy --check-untyped-defs --explicit-package-bases --namespace-packages
    - name: Run golden tests
      run: |
        pytest integration_tests.py::test_hello_program
        pytest integration_tests.py::test_cat_program
        pytest integration_tests.py::test_prob5_program
